Collections:
- Name: hrnet_atrw
  Metadata:
    Architecture:
    - HRNet
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/hrnet_atrw.md
  Paper:
  - http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  - https://arxiv.org/abs/1906.05586
Models:
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--atrw--hrnet_w32_atrw_256x256
  In Collection: hrnet_atrw
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/hrnet_w32_atrw_256x256.py
  Metadata:
    Training Data: ATRW
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: ATRW
    Metrics:
      AP: 0.912
      AP@0.5: 0.973
      AP@0.75: 0.959
      AR: 0.938
      AR@0.5: 0.985
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_atrw_256x256-f027f09a_20210414.pth
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--atrw--hrnet_w48_atrw_256x256
  In Collection: hrnet_atrw
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/hrnet_w48_atrw_256x256.py
  Metadata:
    Training Data: ATRW
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: ATRW
    Metrics:
      AP: 0.911
      AP@0.5: 0.972
      AP@0.75: 0.946
      AR: 0.937
      AR@0.5: 0.985
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w48_atrw_256x256-ac088892_20210414.pth
