Collections:
- Name: hourglass_coco
  Metadata:
    Architecture:
    - Hourglass
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hourglass_coco.md
  Paper:
  - https://link.springer.com/chapter/10.1007/978-3-319-46484-8_29
  - https://link.springer.com/chapter/10.1007/978-3-319-10602-1_48
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--hourglass52_coco_256x256
  In Collection: hourglass_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hourglass52_coco_256x256.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.726
      AP@0.5: 0.896
      AP@0.75: 0.799
      AR: 0.78
      AR@0.5: 0.934
  Weights: https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_coco_256x256-4ec713ba_20200709.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--hourglass52_coco_384x384
  In Collection: hourglass_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hourglass52_coco_384x384.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.746
      AP@0.5: 0.9
      AP@0.75: 0.813
      AR: 0.797
      AR@0.5: 0.939
  Weights: https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_coco_384x384-be91ba2b_20200812.pth
