Collections:
- Name: hrnet_coco
  Metadata:
    Architecture:
    - HRNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_coco.md
  Paper:
  - http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  - https://link.springer.com/chapter/10.1007/978-3-319-10602-1_48
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--hrnet_w32_coco_256x192
  In Collection: hrnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.746
      AP@0.5: 0.904
      AP@0.75: 0.819
      AR: 0.799
      AR@0.5: 0.942
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--hrnet_w32_coco_384x288
  In Collection: hrnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_384x288.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.76
      AP@0.5: 0.906
      AP@0.75: 0.829
      AR: 0.81
      AR@0.5: 0.943
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_384x288-d9f0d786_20200708.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--hrnet_w48_coco_256x192
  In Collection: hrnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.756
      AP@0.5: 0.907
      AP@0.75: 0.825
      AR: 0.806
      AR@0.5: 0.942
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--hrnet_w48_coco_384x288
  In Collection: hrnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_384x288.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.767
      AP@0.5: 0.91
      AP@0.75: 0.831
      AR: 0.816
      AR@0.5: 0.946
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_384x288-314c8528_20200708.pth
