Collections:
- Name: shufflenetv1_coco
  Metadata:
    Architecture:
    - ShufflenetV1
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/shufflenetv1_coco.md
  Paper:
  - http://openaccess.thecvf.com/content_cvpr_2018/html/Zhang_ShuffleNet_An_Extremely_CVPR_2018_paper.html
  - https://link.springer.com/chapter/10.1007/978-3-319-10602-1_48
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--shufflenetv1_coco_256x192
  In Collection: shufflenetv1_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/shufflenetv1_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.585
      AP@0.5: 0.845
      AP@0.75: 0.65
      AR: 0.651
      AR@0.5: 0.894
  Weights: https://download.openmmlab.com/mmpose/top_down/shufflenetv1/shufflenetv1_coco_256x192-353bc02c_20200727.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--shufflenetv1_coco_384x288
  In Collection: shufflenetv1_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/shufflenetv1_coco_384x288.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.622
      AP@0.5: 0.859
      AP@0.75: 0.685
      AR: 0.684
      AR@0.5: 0.901
  Weights: https://download.openmmlab.com/mmpose/top_down/shufflenetv1/shufflenetv1_coco_384x288-b2930b24_20200804.pth
