Collections:
- Name: hrnet_aic
  Metadata:
    Architecture:
    - Associative Embedding
    - HRNet
  README: configs/body/2d_kpt_sview_rgb_img/associative_embedding/aic/hrnet_aic.md
  Paper:
  - https://arxiv.org/abs/1611.05424
  - http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  - https://arxiv.org/abs/1711.06475
Models:
- Name: body--2d_kpt_sview_rgb_img--associative_embedding--aic--hrnet_w32_aic_512x512
  In Collection: hrnet_aic
  Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/aic/hrnet_w32_aic_512x512.py
  Metadata:
    Training Data: AI Challenger
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: AI Challenger
    Metrics:
      AP: 0.303
      AP@0.5: 0.697
      AP@0.75: 0.225
      AR: 0.373
      AR@0.5: 0.755
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w32_aic_512x512-77e2a98a_20210131.pth
- Name: body--2d_kpt_sview_rgb_img--associative_embedding--aic--hrnet_w32_aic_512x512
  In Collection: hrnet_aic
  Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/aic/hrnet_w32_aic_512x512.py
  Metadata:
    Training Data: AI Challenger
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: AI Challenger
    Metrics:
      AP: 0.318
      AP@0.5: 0.717
      AP@0.75: 0.246
      AR: 0.379
      AR@0.5: 0.764
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w32_aic_512x512-77e2a98a_20210131.pth
