Collections:
- Name: videopose3d_mpi-inf-3dhp
  Metadata:
    Architecture:
    - VideoPose3D
  README: configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/mpi_inf_3dhp/videopose3d_mpi-inf-3dhp.md
  Paper:
  - http://openaccess.thecvf.com/content_CVPR_2019/html/Pavllo_3D_Human_Pose_Estimation_in_Video_With_Temporal_Convolutions_and_CVPR_2019_paper.html
  - https://ieeexplore.ieee.org/abstract/document/8374605/
Models:
- Name: body--3d_kpt_sview_rgb_vid--video_pose_lift--mpi_inf_3dhp--videopose3d_mpi-inf-3dhp_1frame_fullconv_supervised_gt
  In Collection: videopose3d_mpi-inf-3dhp
  Config: configs/body/3d_kpt_sview_rgb_vid/video_pose_lift/mpi_inf_3dhp/videopose3d_mpi-inf-3dhp_1frame_fullconv_supervised_gt.py
  Metadata:
    Training Data: MPI-INF-3DHP
  Results:
  - Task: Video-based Single-view 3D Human Body Pose Estimation
    Dataset: MPI-INF-3DHP
    Metrics:
      MPJPE: 58.3
      P-MPJPE: 40.6
      3DPCK: 94.1
      3DAUC: 63.1
  Weights: https://download.openmmlab.com/mmpose/body3d/videopose/videopose_mpi-inf-3dhp_1frame_fullconv_supervised_gt-d6ed21ef_20210603.pth
