Collections:
- Name: resnext_mpii
  Metadata:
    Architecture:
    - ResNext
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnext_mpii.md
  Paper:
  - http://openaccess.thecvf.com/content_cvpr_2017/html/Xie_Aggregated_Residual_Transformations_CVPR_2017_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2014/html/Andriluka_2D_Human_Pose_2014_CVPR_paper.html
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--resnext152_mpii_256x256
  In Collection: resnext_mpii
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnext152_mpii_256x256.py
  Metadata:
    Training Data: MPII
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: MPII
    Metrics:
      Mean: 0.887
      Mean@0.1: 0.294
  Weights: https://download.openmmlab.com/mmpose/top_down/resnext/resnext152_mpii_256x256-df302719_20200927.pth
