Collections:
- Name: hrnetv2_panoptic2d
  Metadata:
    Architecture:
    - HRNetv2
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/hrnetv2_panoptic2d.md
  Paper:
  - https://ieeexplore.ieee.org/abstract/document/9052469/
  - http://openaccess.thecvf.com/content_cvpr_2017/html/Simon_Hand_Keypoint_Detection_CVPR_2017_paper.html
Models:
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--panoptic2d--hrnetv2_w18_panoptic_256x256
  In Collection: hrnetv2_panoptic2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/hrnetv2_w18_panoptic_256x256.py
  Metadata:
    Training Data: CMU Panoptic HandDB
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: CMU Panoptic HandDB
    Metrics:
      PCKh@0.7: 0.999
      AUC: 0.744
      EPE: 7.79
  Weights: https://download.openmmlab.com/mmpose/hand/hrnetv2/hrnetv2_w18_panoptic_256x256-53b12345_20210330.pth
