Collections:
- Name: resnet_interhand2d
  Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/resnet_interhand2d.md
  Paper:
  - http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - https://link.springer.com/content/pdf/10.1007/978-3-030-58565-5_33.pdf
Models:
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--interhand2d--res50_interhand2d_human_256x256
  In Collection: resnet_interhand2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_human_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      PCK@0.2: 0.973
      AUC: 0.828
      EPE: 5.15
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_human-77b27d1a_20201029.pth
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--interhand2d--res50_interhand2d_human_256x256
  In Collection: resnet_interhand2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_human_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      PCK@0.2: 0.973
      AUC: 0.826
      EPE: 5.27
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_human-77b27d1a_20201029.pth
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--interhand2d--res50_interhand2d_human_256x256
  In Collection: resnet_interhand2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_human_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      PCK@0.2: 0.975
      AUC: 0.841
      EPE: 4.9
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_human-77b27d1a_20201029.pth
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--interhand2d--res50_interhand2d_human_256x256
  In Collection: resnet_interhand2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_human_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      PCK@0.2: 0.975
      AUC: 0.839
      EPE: 4.97
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_human-77b27d1a_20201029.pth
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--interhand2d--res50_interhand2d_machine_256x256
  In Collection: resnet_interhand2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_machine_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      PCK@0.2: 0.97
      AUC: 0.824
      EPE: 5.39
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_machine-8f3efe9a_20201102.pth
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--interhand2d--res50_interhand2d_machine_256x256
  In Collection: resnet_interhand2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_machine_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      PCK@0.2: 0.969
      AUC: 0.821
      EPE: 5.52
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_machine-8f3efe9a_20201102.pth
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--interhand2d--res50_interhand2d_machine_256x256
  In Collection: resnet_interhand2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_machine_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      PCK@0.2: 0.972
      AUC: 0.838
      EPE: 5.03
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_machine-8f3efe9a_20201102.pth
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--interhand2d--res50_interhand2d_machine_256x256
  In Collection: resnet_interhand2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_machine_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      PCK@0.2: 0.972
      AUC: 0.837
      EPE: 5.11
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_machine-8f3efe9a_20201102.pth
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--interhand2d--res50_interhand2d_all_256x256
  In Collection: resnet_interhand2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_all_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      PCK@0.2: 0.977
      AUC: 0.84
      EPE: 4.66
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_all-78cc95d4_20201102.pth
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--interhand2d--res50_interhand2d_all_256x256
  In Collection: resnet_interhand2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_all_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      PCK@0.2: 0.979
      AUC: 0.839
      EPE: 4.65
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_all-78cc95d4_20201102.pth
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--interhand2d--res50_interhand2d_all_256x256
  In Collection: resnet_interhand2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_all_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      PCK@0.2: 0.979
      AUC: 0.838
      EPE: 4.42
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_all-78cc95d4_20201102.pth
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--interhand2d--res50_interhand2d_all_256x256
  In Collection: resnet_interhand2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/interhand2d/res50_interhand2d_all_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      PCK@0.2: 0.979
      AUC: 0.851
      EPE: 4.46
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_interhand2d_256x256_all-78cc95d4_20201102.pth
