Collections:
- Name: hrnet_aic
  Metadata:
    Architecture:
    - HRNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/aic/hrnet_aic.md
  Paper:
  - http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  - https://arxiv.org/abs/1711.06475
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--aic--hrnet_w32_aic_256x192
  In Collection: hrnet_aic
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/aic/hrnet_w32_aic_256x192.py
  Metadata:
    Training Data: AI Challenger
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: AI Challenger
    Metrics:
      AP: 0.323
      AP@0.5: 0.762
      AP@0.75: 0.219
      AR: 0.366
      AR@0.5: 0.789
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_aic_256x192-30a4e465_20200826.pth
