Collections:
- Name: hrnetv2_aflw
  Metadata:
    Architecture:
    - HRNetv2
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/aflw/hrnetv2_aflw.md
  Paper:
  - https://ieeexplore.ieee.org/abstract/document/9052469/
  - https://ieeexplore.ieee.org/abstract/document/6130513/
Models:
- Name: face--2d_kpt_sview_rgb_img--topdown_heatmap--aflw--hrnetv2_w18_aflw_256x256
  In Collection: hrnetv2_aflw
  Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/aflw/hrnetv2_w18_aflw_256x256.py
  Metadata:
    Training Data: AFLW
  Results:
  - Task: 2D Face Landmark Detection
    Dataset: AFLW
    Metrics:
      NME full: 1.41
      NME frontal: 1.27
  Weights: https://download.openmmlab.com/mmpose/face/hrnetv2/hrnetv2_w18_aflw_256x256-f2bbc62b_20210125.pth
