Collections:
- Name: mobilenetv2_onehand10k
  Metadata:
    Architecture:
    - MobilenetV2
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/onehand10k/mobilenetv2_onehand10k.md
  Paper:
  - http://openaccess.thecvf.com/content_cvpr_2018/html/Sandler_MobileNetV2_Inverted_Residuals_CVPR_2018_paper.html
  - https://ieeexplore.ieee.org/abstract/document/8529221/
Models:
- Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--onehand10k--mobilenetv2_onehand10k_256x256
  In Collection: mobilenetv2_onehand10k
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/onehand10k/mobilenetv2_onehand10k_256x256.py
  Metadata:
    Training Data: OneHand10K
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: OneHand10K
    Metrics:
      PCK@0.2: 0.986
      AUC: 0.537
      EPE: 28.6
  Weights: https://download.openmmlab.com/mmpose/hand/mobilenetv2/mobilenetv2_onehand10k_256x256-f3a3d90e_20210330.pth
