# -*- coding: utf-8 -*-

KEY_NAME = [
    "nose",
    "center_forehead",
    "end_mouth",
    "center_mouth",
    "neck",
    "front_right_shoulder",
    "front_left_shoulder",
    "front_right_ankle",
    "front_left_ankle",
    "back_right_femur",
    "back_left_femur",
    "back_right_ankle",
    "back_left_ankle",
    "tail_start",
    "tail_end",
]
SKELETON = [
        [0,1],[1,2],[2,3],[0,4],[1,4],[3,4],
        [4,13],
        [4,5],[4,6],[5,7],[6,8],
        [13,9],[13,10],[9,11],[10,12],
        [13,14]
    ]

SPECIES ={
    '말티즈': 'maltese',
    '푸들': 'poodle',
    '셔틀랜드 쉽독': "Shetland Sheepdog",
    '미니어처 핀셔': "miniature pinscher",
    '믹스견': "mixed dog",
    '프렌치 불독': "french bulldog",
    '포메라니안': "Pomeranian",
    '재패니스 스피츠': "Japanese Spitz",
    '진돗개': "Jindo dog",
    '비숑 프리제': "Bichon Frize",
    '파피용': "papillon",
    '골든 리트리버': "golden retriever",
    '웰시 코기 (펨브록)': "Welsh Corgi (Pembroke)",
    '닥스훈트': "dachshund",
    '웰시 코기 (카디건)': "Welsh Corgi (Cardigan)",
    '시추': "Shih Tzu",
    '시바': "Shiba Inu",
    '아메리칸 코커 스패니얼': "american cocker spaniel",
    '치와와': "Chihuahua",
    '시베리안 허스키': "Siberian husky",
    '페키니즈': "Pekingese",
    '스탠다드 푸들': "standard poodle",
    '보더 콜리': "border collie",
    '풍산개': "Poongsan Dog",
    '보스턴 테리어': "Boston Terrier",
    '올드 잉글리시 쉽독': "old english sheepdog",
    '요크셔 테리어': "Yorkshire terrier",
    '피니시 스피츠': "finish spitz",
    '오스트레일리안 실키 테리어': "Australian Silky Terrier",
    '이탈리안 그레이하운드': "Italian Greyhound",
    '래브라도 리트리버': "Labrador dog",
    '독일 스피츠': "german spitz",
    '잉글리시 코커 스패니얼': "english cocker spaniel",
    '미니어처 슈나우저': "miniature schnauzer",
    '퍼그': "pug",
    '로트바일러': "Rottweiler",
    '베들링턴 테리어': "Bedlington Terrier",
    '사모예드견': "samoyed dog",
    '샤페이': "Shar Pei",
    '카발리에 킹 찰스 스패니얼': "Cavalier King Charles Spaniel",
    '삽살개': "Sapsalgae",
    '그리폰 비글': "griffon beagle",
    '달마티안': "Dalmatian",
    '비글': "beagle",
    '아메리칸 불독': "american bulldog",
    '도베르만': "doberman",
    '잭 러셀 테리어': "Jack Russell Terrier",
    '스코티시 테리어': "scottish terrier",
    '슈나우저': "schnauzer",
    '아메리칸 불리': "American Bully",
    '코통 드 튈레아르': "Coton de Tuileire",
    '라사 압소': "Lhasa Apso",
    '와이어 폭스 테리어': "wire fox terrier",
    '코리안 숏헤어': "Korean short hair",
    '러시안블루': "Russian Blue",
    '노르웨이숲': "norwegian forest",
    '먼치킨': "Munchkin",
    '벵갈': "bengal",
    '스코티쉬 폴드 롱헤어': "scottish fold long hair",
    '브리티쉬 숏헤어': "british short hair",
    '스코티쉬 폴드': "scottish fold",
    '페르시안': "Persian",
    '라팜 숏헤어': "Rafaam Shorthair",
    '터키시 앙고라': "Turkish Angora",
    '래그돌': "ragdoll",
    '시암': "Siam",
    '아메리칸 숏헤어': "american shorthair",
    '스코티쉬 스트레이드': "scottish straight",
    '스코티쉬 스트레이드 롱헤어': "scottish straight long hair",
    '먼치킨 롱헤어': "Munchkin long hair",
    '아비시니안': "Abyssinian",
    '스노우슈': "snowshoe",
    '소말리': "Somali",
    '맹크스': "Manx",
    '엑조틱 숏헤어': "Exotic short hair",
    '아메리칸 컬': "american curl",
    '코랏': "korat",
    '시베리안': "siberian",
    '발리니즈': "Balinese",
    '재패니즈밥테일': "Japanese Bobtail",
    '나폴레옹': "Napoleon",
    '돈스코이': "Donskoy",
    '네벨룽': "Nebelung",
    '스핑크스': "sphinx",
    '샤르트뢰': "Chartreux",
    '라팜': "Rafaam",
    '버마': "Burma",
    '메인 쿤': "maine coon",
    '터키시 반': "turkish half",
    '브리티쉬 롱헤어': "british long hair",
    '데본렉스': "Devon Rex",
    '라이코이': "Raikoy"
}

INFO = {
    'description': 'AI Hub Dataset', 
    'url': 'https://aihub.or.kr/aidata/34146', 
    'version': '1.0', 
    'year': 2021
    }

LICENSES = [
    {'url': 'http://lifelibrary.synology.me', 'id': 0, 'name': 'Attribution-NonCommercial-ShareAlike License'},
    
    ]


CAT_ACTS = {
    '꼬리를 흔든다': 7,
    '팔을 뻗어 휘적거림': 11,
    '옆으로 누워 있음': 10,
    '앞발을 뻗어 휘적거리는 동작': 11,
    '옆으로 눕는 동작': 10,
    '꼬리를 흔드는 동작': 7,
    '앞발로 꾹꾹 누름': 8,
    '발을 숨기고 웅크리고 앉음': 2,
    '납작 엎드림': 1,
    '허리를 아치로 세움': 9,
    '배를 보임': 6,
    '좌우로 뒹굴음': 4,
    '허리를 아치로 세우는 동작': 9,
    '앞발로 꾹꾹 누르는 동작': 8,
    '납작 엎드리는 동작': 1,
    '머리를 들이댐': 5,
    '머리를 들이대는 동작': 5,
    '배를 보이는 동작': 6,
    '좌우로 뒹구는 동작': 4,
    '발을 숨기고 웅크리고 앉는 동작': 2,
    '배를 보여주는 동작': 6,
    '그루밍함': 3,
    '그루밍하는 동작': 3,
    '걷거나 뛰는 동작': 12,
    '걷거나 뜀 ': 12,
    '걷거나 달리는 동작': 12
}

DOG_ACTS = {
    '걷거나 뜀': 13,
    '걷거나 뜀 ': 13,
    '걷거나 뛰는 동작': 13,
    '걷거나 달리는 동작': 13,
    '앞발 하나를 들어 올림': 3,
    '꼬리가 아래로 향함': 10,
    '마운팅': 9,
    '앞발 하나를 들어 올리는 동작': 3,
    '마운팅하는 동작': 9,
    '꼬리를 아래로 내리는 동작': 10,
    '엎드리기(몸체를 낮게 유지)': 5,
    '몸을 턴다': 4,
    '엎드리는 동작(몸체를 낮게 유지)': 5,
    '몸을 터는 동작': 4,
    '엎드리는 동작': 5,
    '앉기': 11,
    '빙글빙글 돈다': 8,
    '빙글빙들 돈다': 8,
    '앉는 동작': 11,
    '빙글빙글 도는 동작': 8,
    '두 앞발을 들어 올림': 2,
    '꼬리를 위로 올리고 흔듦': 7,
    '꼬리를 흔듦': 7,
    '두 앞발을 들어 올리는 동작': 2,
    '꼬리를 위로 올리고 흔드는 동작': 7,
    '배와 목을 보여주며 누움': 6,
    '머리를 앞으로 들이댐': 1,
    '몸을 긁는 동작': 12,
    '머리를 앞으로 들이미는 동작': 1,
    '배와 목을 보여주며 눕는 동작': 6,
    '몸을 긁음': 12,
    '머리를 들이대는 동작': 1
}
