# -*- coding: utf-8 -*-

KEY_NAME = [
    "nose",
    "center_forehead",
    "end_mouth",
    "center_mouth",
    "neck",
    "front_right_shoulder",
    "front_left_shoulder",
    "front_right_ankle",
    "front_left_ankle",
    "back_right_femur",
    "back_left_femur",
    "back_right_ankle",
    "back_left_ankle",
    "tail_start",
    "tail_end",
]
SKELETON = [
        [0,1],[1,2],[2,3],[0,4],[1,4],[3,4],
        [4,13],
        [4,5],[4,6],[5,7],[6,8],
        [13,9],[13,10],[9,11],[10,12],
        [13,14]
    ]

SPECIES ={
    '말티즈': 'maltese',
    '푸들': 'poodle',
    '셔틀랜드 쉽독': "Shetland Sheepdog",
    '미니어처 핀셔': "miniature pinscher",
    '믹스견': "mixed dog",
    '프렌치 불독': "french bulldog",
    '포메라니안': "Pomeranian",
    '재패니스 스피츠': "Japanese Spitz",
    '진돗개': "Jindo dog",
    '비숑 프리제': "Bichon Frize",
    '파피용': "papillon",
    '골든 리트리버': "golden retriever",
    '웰시 코기 (펨브록)': "Welsh Corgi (Pembroke)",
    '닥스훈트': "dachshund",
    '웰시 코기 (카디건)': "Welsh Corgi (Cardigan)",
    '시추': "Shih Tzu",
    '시바': "Shiba Inu",
    '아메리칸 코커 스패니얼': "american cocker spaniel",
    '치와와': "Chihuahua",
    '시베리안 허스키': "Siberian husky",
    '페키니즈': "Pekingese",
    '스탠다드 푸들': "standard poodle",
    '보더 콜리': "border collie",
    '풍산개': "Poongsan Dog",
    '보스턴 테리어': "Boston Terrier",
    '올드 잉글리시 쉽독': "old english sheepdog",
    '요크셔 테리어': "Yorkshire terrier",
    '피니시 스피츠': "finish spitz",
    '오스트레일리안 실키 테리어': "Australian Silky Terrier",
    '이탈리안 그레이하운드': "Italian Greyhound",
    '래브라도 리트리버': "Labrador dog",
    '독일 스피츠': "german spitz",
    '잉글리시 코커 스패니얼': "english cocker spaniel",
    '미니어처 슈나우저': "miniature schnauzer",
    '퍼그': "pug",
    '로트바일러': "Rottweiler",
    '베들링턴 테리어': "Bedlington Terrier",
    '사모예드견': "samoyed dog",
    '샤페이': "Shar Pei",
    '카발리에 킹 찰스 스패니얼': "Cavalier King Charles Spaniel",
    '삽살개': "Sapsalgae",
    '그리폰 비글': "griffon beagle",
    '달마티안': "Dalmatian",
    '비글': "beagle",
    '아메리칸 불독': "american bulldog",
    '도베르만': "doberman",
    '잭 러셀 테리어': "Jack Russell Terrier",
    '스코티시 테리어': "scottish terrier",
    '슈나우저': "schnauzer",
    '아메리칸 불리': "American Bully",
    '코통 드 튈레아르': "Coton de Tuileire",
    '라사 압소': "Lhasa Apso",
    '와이어 폭스 테리어': "wire fox terrier",
    '코리안 숏헤어': "Korean short hair",
    '러시안블루': "Russian Blue",
    '노르웨이숲': "norwegian forest",
    '먼치킨': "Munchkin",
    '벵갈': "bengal",
    '스코티쉬 폴드 롱헤어': "scottish fold long hair",
    '브리티쉬 숏헤어': "british short hair",
    '스코티쉬 폴드': "scottish fold",
    '페르시안': "Persian",
    '라팜 숏헤어': "Rafaam Shorthair",
    '터키시 앙고라': "Turkish Angora",
    '래그돌': "ragdoll",
    '시암': "Siam",
    '아메리칸 숏헤어': "american shorthair",
    '스코티쉬 스트레이드': "scottish straight",
    '스코티쉬 스트레이드 롱헤어': "scottish straight long hair",
    '먼치킨 롱헤어': "Munchkin long hair",
    '아비시니안': "Abyssinian",
    '스노우슈': "snowshoe",
    '소말리': "Somali",
    '맹크스': "Manx",
    '엑조틱 숏헤어': "Exotic short hair",
    '아메리칸 컬': "american curl",
    '코랏': "korat",
    '시베리안': "siberian",
    '발리니즈': "Balinese",
    '재패니즈밥테일': "Japanese Bobtail",
    '나폴레옹': "Napoleon",
    '돈스코이': "Donskoy",
    '네벨룽': "Nebelung",
    '스핑크스': "sphinx",
    '샤르트뢰': "Chartreux",
    '라팜': "Rafaam",
    '버마': "Burma",
    '메인 쿤': "maine coon",
    '터키시 반': "turkish half",
    '브리티쉬 롱헤어': "british long hair",
    '데본렉스': "Devon Rex",
    '라이코이': "Raikoy"
}

INFO = {
    'description': 'AI Hub Dataset', 
    'url': 'https://aihub.or.kr/aidata/34146', 
    'version': '1.0', 
    'year': 2021
    }

LICENSES = [
    {'url': 'http://lifelibrary.synology.me', 'id': 0, 'name': 'Attribution-NonCommercial-ShareAlike License'},
    
    ]
