Collections:
- Name: hrnet_animalpose
  Metadata:
    Architecture:
    - HRNet
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/hrnet_animalpose.md
  Paper:
  - http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  - http://openaccess.thecvf.com/content_ICCV_2019/html/Cao_Cross-Domain_Adaptation_for_Animal_Pose_Estimation_ICCV_2019_paper.html
Models:
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--animalpose--hrnet_w32_animalpose_256x256
  In Collection: hrnet_animalpose
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/hrnet_w32_animalpose_256x256.py
  Metadata:
    Training Data: Animal-Pose
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Animal-Pose
    Metrics:
      AP: 0.736
      AP@0.5: 0.959
      AP@0.75: 0.832
      AR: 0.775
      AR@0.5: 0.966
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_animalpose_256x256-1aa7f075_20210426.pth
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--animalpose--hrnet_w48_animalpose_256x256
  In Collection: hrnet_animalpose
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/hrnet_w48_animalpose_256x256.py
  Metadata:
    Training Data: Animal-Pose
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Animal-Pose
    Metrics:
      AP: 0.737
      AP@0.5: 0.959
      AP@0.75: 0.823
      AR: 0.778
      AR@0.5: 0.962
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w48_animalpose_256x256-34644726_20210426.pth
