Collections:
- Name: resnet_fly
  Metadata:
    Architecture:
    - SimpleBaseline2D
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/fly/resnet_fly.md
  Paper:
  - http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - https://www.nature.com/articles/s41592-018-0234-5
Models:
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--fly--res50_fly_192x192
  In Collection: resnet_fly
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/fly/res50_fly_192x192.py
  Metadata:
    Training Data: Vinegar Fly
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Vinegar Fly
    Metrics:
      PCK@0.2: 0.996
      AUC: 0.91
      EPE: 2.0
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_fly_192x192-5d0ee2d9_20210407.pth
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--fly--res101_fly_192x192
  In Collection: resnet_fly
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/fly/res101_fly_192x192.py
  Metadata:
    Training Data: Vinegar Fly
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Vinegar Fly
    Metrics:
      PCK@0.2: 0.996
      AUC: 0.912
      EPE: 1.95
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_fly_192x192-41a7a6cc_20210407.pth
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--fly--res152_fly_192x192
  In Collection: resnet_fly
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/fly/res152_fly_192x192.py
  Metadata:
    Training Data: Vinegar Fly
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Vinegar Fly
    Metrics:
      PCK@0.2: 0.997
      AUC: 0.917
      EPE: 1.78
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_fly_192x192-fcafbd5a_20210407.pth
